pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'plannerexandimport:linux'
  dockerId: 'tobiasfenster'

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: '$(dockerId)/$(imageName)'
    dockerfile: 'Dockerfile.linux'
- task: Docker@1
  displayName: Login
  inputs:
    command: login
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'docker_hub_connection'
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: '$(dockerId)/$(imageName)'
