parameters:
  os: ''
  vmImage: ''

jobs:
- job: ${{ parameters.os }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  variables:
    imageName: ${{ format('plannerexandimport:{0}', parameters.os) }}
    dockerId: 'tobiasfenster'
  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      imageName: '$(dockerId)/$(imageName)'
      dockerfile: ${{ format('Dockerfile.{0}', parameters.os) }}
  - task: Docker@1
    displayName: Login
    inputs:
      command: login
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'docker_hub_connection'
  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      command: 'push'
      imageName: '$(dockerId)/$(imageName)'
