jobs:
- job: manifest
  pool: 
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Docker@1
    displayName: Login
    inputs:
      command: login
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'docker_hub_connection'
  - powershell: |
     if (!(Test-Path ~/.docker)) { mkdir ~/.docker }
     '{ "experimental": "enabled" }' | Out-File ~/.docker/config.json -Encoding Ascii
     docker --config ~/.docker manifest create tobiasfenster/plannerexandimport:latest  tobiasfenster/plannerexandimport:linux tobiasfenster/plannerexandimport:windows
     docker --config ~/.docker manifest push tobiasfenster/plannerexandimport:latest 
    displayName: 'Create Manifest' 
   