jobs:
- template: azure-pipelines.jobtemplate.yml
  parameters:
    os: linux
    vmImage: 'Ubuntu 16.04'

- template: azure-pipelines.jobtemplate.yml
  parameters:
    os: windows
    vmImage: 'VS2017-Win2016'
