parameters:
  os: ''
  vmImage: ''
  sdk: ''
  runtime: ''

jobs:
- job: ${{ parameters.os }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  variables:
    imageName: ${{ format('plannerexandimport:{0}', parameters.os) }}
    dockerId: 'tobiasfenster'
  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      arguments: ${{ format('--build-arg SDK={0} --build-arg RUNTIME={1}', parameters.sdk, parameters.runtime) }}
      imageName: '$(dockerId)/$(imageName)'
  - task: Docker@1
    displayName: Login
    inputs:
      command: login
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'docker_hub_connection'
  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      command: 'push'
      imageName: '$(dockerId)/$(imageName)'
