jobs:
- template: azure-pipelines.jobtemplate.yml
  parameters:
    os: linux
    vmImage: ubuntu-1604

- template: azure-pipelines.jobtemplate.yml
  parameters:
    os: windows
    vmImage: vs2017-win2016
